version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-major}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - /mnt/aayush/major-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    image: quay.io/agcdev0/major-project:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      DB_NAME: major
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      OLLAMA_API_BASE: http://ollama:11434

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/aayush/ollama:/root/.ollama
    networks:
      - backend
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c", "ollama serve & sleep 5 && ollama pull mistral && tail -f /dev/null"]

volumes:
  postgres_data:
