version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-major}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - /mnt/aayush/major-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
